<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Reminders.NotificationSenderWorker-335eff36-79cf-4f8b-b077-6e8c70ec89be</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Reminders.Application\Reminders.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="appsettings.json">
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </Content>
        <Content Update="appsettings.Development.json">
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </Content>
    </ItemGroup>
</Project>
