// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reminders.Infrastructure.Contexts;

#nullable disable

namespace Reminders.Infrastructure.Migrations
{
    [DbContext(typeof(RemindersContext))]
    partial class RemindersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReminderUser", b =>
                {
                    b.Property<Guid>("MembersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uuid");

                    b.HasKey("MembersId", "ReminderId");

                    b.HasIndex("ReminderId");

                    b.ToTable("ReminderMembers", (string)null);
                });

            modelBuilder.Entity("Reminders.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("время создания");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasComment("id создателя");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Описание");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Название");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasComment("Категории");
                        });
                });

            modelBuilder.Entity("Reminders.Domain.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Id");

                    b.Property<int>("IsProcessed")
                        .HasColumnType("integer")
                        .HasComment("статус обработки");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("время напоминания");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasComment("id получателя");

                    b.Property<int>("Recurrency")
                        .HasColumnType("integer")
                        .HasComment("Повтор напоминания");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uuid")
                        .HasComment("id напоминания");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("ReminderId");

                    b.HasIndex("IsProcessed", "NotificationTime");

                    b.ToTable("Notifications", null, t =>
                        {
                            t.HasComment("Уведомления");
                        });
                });

            modelBuilder.Entity("Reminders.Domain.Models.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasComment("id категории");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время завершения");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("время создания");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasComment("id создателя");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Описание");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дедлайн");

                    b.Property<int>("IsCompleted")
                        .HasColumnType("integer")
                        .HasComment("Статус завершения");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasComment("Приоритет");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Название");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Reminders", null, t =>
                        {
                            t.HasComment("Напоминания");
                        });
                });

            modelBuilder.Entity("Reminders.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("время создания");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("хэшированный пароль");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("имя пользователя");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasComment("Пользователи");
                        });
                });

            modelBuilder.Entity("ReminderUser", b =>
                {
                    b.HasOne("Reminders.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reminders.Domain.Models.Reminder", null)
                        .WithMany()
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reminders.Domain.Models.Category", b =>
                {
                    b.HasOne("Reminders.Domain.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Reminders.Domain.Models.Notification", b =>
                {
                    b.HasOne("Reminders.Domain.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reminders.Domain.Models.Reminder", "Reminder")
                        .WithMany()
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("Reminders.Domain.Models.Reminder", b =>
                {
                    b.HasOne("Reminders.Domain.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reminders.Domain.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Creator");
                });
#pragma warning restore 612, 618
        }
    }
}
